---
- name: haveged
  hosts: rancherserver
  sudo: True
  tasks:
  - name: Make sure Docker is running
    service: >
      name=docker
      state=started
      enabled=yes
  - name: Entropy maker HAVEGED
    docker:
      name: havegedocker
      image: joshuacox/havegedocker:latest
      privileged: yes
      state: reloaded
