---
- name: Rancher Server
  hosts: rancherserver
  sudo: True
  tasks:
  - name: Make sure Docker is running
    service: >
      name=docker
      state=started
      enabled=yes
  - name: Ensure rancher/server container is running
    docker:
      name: rancherserver
      image: rancher/server
      state: reloaded
      restart_policy: always
      ports:
      - "8080:8080"
