---
- name: Rancher Agent
  hosts: rancheragent
  vars:
     url_contents: "{{ lookup('file', 'url') }}"
     ip_contents: "{{ lookup('file', 'ip') }}"
     labels_contents: "{{ lookup('file', 'labels') }}"
  sudo: True
  tasks:
  - name: Ensure rancher/agent container is running
    docker:
      name: rancheragent
      image: rancher/agent:v0.7.9
      privileged: True
      # Change to 'reloaded' after this is fixed: https://github.com/ansible/ansible-modules-core/issues/2257
      state: started
      restart_policy: always
      volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      command: "{{ url_contents }}"
      env:
        CATTLE_AGENT_IP: "{{ ip_contents }}"
        CATTLE_HOST_LABELS: "{{ labels_contents }}"
